cabal-version:      3.4
name:               exception-rethrowing-experiments
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Daniel Díaz
maintainer:         diaz_carrete@yahoo.com
-- copyright:
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

common backtraces
    ghc-options: 
        -O0 
        -finfo-table-map 
        -fdistinct-constructor-tables

library
    import:           warnings, backtraces
    exposed-modules:  PrettyException
    -- other-modules:
    -- other-extensions:
    build-depends:    base ^>=4.22.0.0,
                      containers
    hs-source-dirs:   lib
    default-language: GHC2024

executable exception-rethrowing-experiments
    import:           warnings, backtraces
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:
    build-depends:
        base ^>=4.22.0.0,
        exception-rethrowing-experiments

    hs-source-dirs:   app
    default-language: GHC2024

test-suite exception-rethrowing-experiments-test
    import:           warnings, backtraces
    default-language: GHC2024
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base ^>=4.22.0.0,
        exception-rethrowing-experiments
